Ditch bizarre inclusion-then-mock-out of matplotlib from sphinx
A long time ago, commit ff358b3 - "add plotting to conf.py" -
added several plotting-related sphinx modules provided by
matplotlib to the sphinx config. Notably, it did not actually
add any *use* of these modules, so far as I can tell. Neither
did anything else later, again so far as I can tell.

Bizarrely, commit 9323618 - which followed it a month later -
proceeded to *mock these modules and their dependencies right
back out again*.

I have no idea what the idea was here, but it seems rather
weird. More to the point, it breaks build of the docs with
recent Sphinx, as this artisanal Mock() implementation is not
iterable:

Exception occurred:
  File "/usr/lib/python2.7/site-packages/sphinx/registry.py", line 225, in load_extension
    app.extensions[extname] = Extension(extname, mod, **metadata)
TypeError: 'Mock' object is not iterable

So, let's throw out this entire edifice of zaniness. The docs
build just fine with the remaining matplotlib module (the others
got taken out over the years) cut out from the extensions list,
and the whole weird Mock bit chopped.

Signed-off-by: Adam Williamson <awilliam@redhat.com>